import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AuthPanel } from "../auth/AuthPanel";
export function Sidebar(props) {
    return (_jsxs("aside", { className: "sidebar", children: [_jsxs("div", { className: "brand-block", children: [_jsx("p", { className: "eyebrow", children: "AI Ops for Documents & Visual Data" }), _jsx("h1", { children: "Summaries, answers, and saved work from one shared workspace." }), _jsx("p", { className: "brand-copy", children: "Bring in documents, screenshots, and microphone notes. Then keep the useful sessions attached to the right user account." }), _jsxs("div", { className: "brand-stats", children: [_jsxs("div", { className: "brand-stat", children: [_jsx("strong", { children: props.mode === "authenticated" ? "Saved" : "Guest" }), _jsx("span", { children: "access mode" })] }), _jsxs("div", { className: "brand-stat", children: [_jsx("strong", { children: props.chats.length }), _jsx("span", { children: props.mode === "authenticated" ? "saved sessions" : "current sessions" })] })] }), _jsxs("div", { className: "brand-actions", children: [_jsx("button", { className: "button", onClick: props.onNewChat, children: "New session" }), _jsx("button", { className: "button button-secondary", onClick: props.onClearChat, children: "Clear chat" })] })] }), _jsx(AuthPanel, { mode: props.mode, userEmail: props.userEmail, onOpenAccess: props.onOpenAccess, onSignOut: props.onSignOut }), _jsxs("section", { className: "panel history-panel", children: [_jsxs("div", { className: "panel-header", children: [_jsx("h2", { children: props.mode === "authenticated" ? "Saved sessions" : "Guest sessions" }), _jsx("span", { className: "muted", children: props.mode === "authenticated" ? "Account history" : "Temporary access" })] }), _jsx("div", { className: "history-list", children: props.chats.length === 0 ? (_jsxs("div", { className: "empty-card", children: [_jsx("p", { children: "No sessions yet." }), _jsx("span", { children: "Start with a prompt, a file upload, or a quick microphone note." })] })) : (props.chats.map((chat) => (_jsxs("button", { className: chat.id === props.activeChatId ? "history-item history-item-active" : "history-item", onClick: () => props.onSelectChat(chat.id), children: [_jsx("span", { children: chat.title }), _jsxs("small", { children: [chat.attachmentCount, " file", chat.attachmentCount === 1 ? "" : "s", " \u2022", " ", new Date(chat.lastMessageAt).toLocaleString([], {
                                            month: "short",
                                            day: "numeric",
                                            hour: "2-digit",
                                            minute: "2-digit"
                                        })] })] }, chat.id)))) })] })] }));
}
